on:
  push:
    branches:
      - main
      - dev
  pull_request:
      types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run make Coverage and test.
      run: make coverage-build

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
